sudo: required

services:
- docker

install: skip

jobs:
  include:
    - &deploy-stage
      stage: deploy
      if: branch = master
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build -t ddclient:$DOCKER_TAG -f $DOCKERFILE .
        - docker run --rm -it ddclient:$DOCKER_TAG --help | grep -A 10 'ddclient version'
      after_success:
        - docker tag ddclient:$DOCKER_TAG rycus86/ddclient:$DOCKER_TAG
        - docker login -u="rycus86" -p="$DOCKER_PASSWORD"
        - docker push rycus86/ddclient:$DOCKER_TAG
      env:
        - DOCKER_TAG=amd64
        - DOCKERFILE=Dockerfile

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=armhf
        - DOCKERFILE=Dockerfile.armhf

    - <<: *deploy-stage
      env:
        - DOCKER_TAG=aarch64
        - DOCKERFILE=Dockerfile.aarch64

    - stage: manifest
      if: branch = master
      script:
        - docker login -u="rycus86" -p="${DOCKER_PASSWORD}"
        - curl -fsSL https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 > ./manifest-tool
        - chmod +x ./manifest-tool
        - ./manifest-tool push from-spec manifest.yml
